Update modDesc.xml
VertexDezign/TargetFillLevel pull request #1
Opened 2023-04-25 17:19 UTC by vitalii2011

2023-04-25 19:56 UTC, schliesser requested changes

2023-04-25 19:56 UTC, schliesser commented on modDesc.xml
> +			<ru>Заполнение ТС</ru>
Hey, thanks for you PR.
shouldn't this be also like the above?
`Уровень Заполнения Транспорта`

2023-04-25 20:41 UTC, vitalii2011 commented on modDesc.xml
> +			<ru>Заполнение ТС</ru>
Where this text is displayed better, so as not to overload the interface, the abbreviation "ТС" = "Транспортное Средство"(transport vehicle) – this includes trucks and trailers.

2023-05-03 06:20 UTC, schliesser commented on modDesc.xml
> +			<ru>Заполнение ТС</ru>
Thx for the clarification. I merge it :-)

2023-05-03 06:20 UTC, schliesser approved these changes

2023-05-03 06:21 UTC, merged